# Generated by Django 4.2.5 on 2023-09-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpeningHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday", models.CharField(max_length=200)),
                ("opening_time", models.CharField(max_length=200)),
                ("closing_time", models.CharField(max_length=200)),
            ],
        ),
    ]
