# Generated by Django 4.2.5 on 2023-09-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0002_openinghours"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manufacturer", models.CharField(max_length=200)),
                ("model_name", models.CharField(max_length=200)),
                ("price", models.FloatField()),
                ("picture", models.ImageField(upload_to="product_images")),
                ("enabled", models.BooleanField()),
                ("year", models.CharField(max_length=200)),
            ],
        ),
    ]
